### ISSUE TITLE
Broken on web

### ISSUE THREAD

**Issue by CiriousJoker** [bnxm/implicitly_animated_reorderable_list#45]
```
Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (2 weeks ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)
```

- I can pick up the item by long pressing, but I cannot move it anywhere
- I also can't release it (stays floating)
- It also doesn't register click events anymore

Not sure if this is a bug with this specific Flutter version. I'll update this once I tried different Flutter versions.

**Comment by CiriousJoker** [comment]
This is the error message:

<details>

<summary>flutter/lib/src/rendering/mouse_tracking.dart:312</summary>

```
Error: Assertion failed:
../…/rendering/mouse_tracking.dart:312
!_debugDuringDeviceUpdate
is not true
    at Object.throw_ [as throw] (http://localhost:8080/dart_sdk.js:4333:11)
    at Object.assertFailed (http://localhost:8080/dart_sdk.js:4280:15)
    at mouse_tracking.MouseTracker.new.[_deviceUpdatePhase] (http://localhost:8080/packages/flutter/src/rendering/layer.dart.lib.js:4940:61)
    at http://localhost:8080/packages/flutter/src/rendering/layer.dart.lib.js:4998:33
    at mouse_tracking.MouseTracker.new.[_monitorMouseConnection] (http://localhost:8080/packages/flutter/src/rendering/layer.dart.lib.js:4935:7)
    at mouse_tracking.MouseTracker.new.updateWithEvent (http://localhost:8080/packages/flutter/src/rendering/layer.dart.lib.js:4997:36)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:8080/packages/flutter/src/rendering/layer.dart.lib.js:5943:45)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (http://localhost:8080/packages/flutter/src/gestures/binding.dart.lib.js:257:14)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:8080/packages/flutter/src/gestures/binding.dart.lib.js:229:35)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:8080/packages/flutter/src/gestures/binding.dart.lib.js:213:65)
    at Object._invoke1 (http://localhost:8080/dart_sdk.js:175458:7)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (http://localhost:8080/dart_sdk.js:171312:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:8080/dart_sdk.js:158216:24)
    at http://localhost:8080/dart_sdk.js:158590:26
    at http://localhost:8080/dart_sdk.js:158562:16
    at http://localhost:8080/dart_sdk.js:158315:11
```

</details>

Seems to be an issue with the framework itself :/

**Comment by cachapa** [comment]
I'm having the exact same issue on Desktop (Linux), but works fine on mobile.

The issue goes away if you remove the onTap callback from ListTile.

[✓] Flutter (Channel master, 1.24.0-4.0.pre.55, on Linux, locale en_US.UTF-8)

**Comment by CiriousJoker** [comment]
@cachapa Thanks for pointing that out!

**Comment by FRANIAZA** [comment]
Same problem, the error log is:
```
Error: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active. 
```
I have no way of removing the on tap method, as I am using ExpansionTiles as items of the reorderable list.

**Comment by FRANIAZA** [comment]
Same problem of #35

**Comment by bnxm** [comment]
I cannot reproduce this with the most recent version. If this issue still persist, feel free to reopen.
