### ISSUE TITLE
 Illegal argument in isolate message - Does not allow for list to work - Major Error

### ISSUE THREAD

**Issue by vk1815918** [bnxm/implicitly_animated_reorderable_list#81]
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object extends NativeWrapper - Library:'dart:io' Class: _RandomAccessFileOpsImpl@13069316)

- This error is thrown randomly and freezes the list, do not allow for items to be added nor deleted.

**Comment by vk1815918** [comment]
`return ValueListenableBuilder<Box<ChatStorage>>(
                        valueListenable: Hive.box<ChatStorage>('${widget.peerID}-chat').listenable(),
                        builder: (context, box, _) {
                          final snapshots = box.values.toList().cast<ChatStorage>();
                           snapshots.sort((a, b) => -(int.parse(a.time)).compareTo(int.parse(b.time)));`

-The `snapshots` is what I am passing into the list, and every time a new item is added it throws an error.

**Comment by vk1815918** [comment]
`class ChatStorage extends HiveObject {
  ChatStorage({@required this.name, @required this.time, @required this.message, @required this.msgType, @required this.isread});
  @HiveField(0)
  String name;
  @HiveField(1)
  dynamic time;
  @HiveField(2)
  String message;
  @HiveField(3)
  dynamic msgType;
  @HiveField(4)
  bool isread;
}`

-This is the class that I am passing into the list.
`ImplicitlyAnimatedList<ChatStorage>(
                                      items: snapshots,
                                      padding: const EdgeInsets.fromLTRB(4.0, 10, 4, 10),
                                      reverse: true,
                                      shrinkWrap: true,
                                      controller: listScrollController,
                                      areItemsTheSame: (a, b) => a.key == b.key,
                                      itemBuilder: (context, animation, item, index) {
                                        return SizeFadeTransition(
                                          sizeFraction: 0.7,
                                          curve: Curves.easeIn,
                                          animation: animation,
                                          child: item.name == widget.name ?
                                              _listItemOther(
                                                  context,
                                                  item.key,
                                                  widget.name,
                                                  widget.profilePic,
                                                  item.message,
                                                  item.time.toString(),
                                                  int.parse(item.msgType),
                                                  item.isread
                                              ) :
                                              _listItemMine(
                                                  context,
                                                  item.key,
                                                  item.message,
                                                  item.time.toString(),
                                                  item.isread,
                                                  int.parse(item.msgType)
                                              )
                                        );
                                      },
                                    )`
-And this is how I am using the list , please do tell me if I am using the list wrong or am not passing parameters correctly.

**Comment by vk1815918** [comment]
I should also mention that the error is very inconsistent and shows up sometimes, especially when there a quite a few entries and delete from the list in a short amount of time.

**Comment by RobertOdrowaz** [comment]
Types of objects that can be passed to an isolate via [`SendPort.send`](https://api.dart.dev/stable/2.14.4/dart-isolate/SendPort/send.html) is very limited. I've encountered the same issue because `T` contained `SplayTreeMap` with a default value of `isValidKey` which is a closure and thus cannot be passed to an isolate. @vk1815918 similarly in your case `HiveObject` doesn't meet the constraints of the `SendPort`. I assume it works sometimes because the field causing the issue may not be initialized by hive yet.

@bxqm I don't think there is anything that can be done about it other than adding a warning to the documentation. The issue is especially easy to miss since isolates are only used once a certain number of items is reached.

**Comment by madurangae** [comment]
I believe the error I'm getting currently is also related to this. Similar to what vk1815918 described, the error seems to appear when the list is populated with about 30 entries.

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a closure - Function '<anonymous closure>':.)
#0      spawnFunction (dart:_internal-patch/internal_patch.dart:190:54)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:362:7)
#2      compute
package:flutter/…/foundation/_isolates_io.dart:22
#3      MyersDiff.diff
package:implicitly_animated_reorderable_list/…/diff/myers_diff.dart:47
#4      MyersDiff.withCallback
package:implicitly_animated_reorderable_list/…/diff/myers_diff.dart:24
#5      ImplicitlyAnimatedListBaseState._calcDiffs
package:implicitly_animated_reorderable_list/src/implicitly_animated_list_base.dart:183
<asynchronous suspension>

**Comment by bxqm** [comment]
You can set the `spawnIsolate` field explicitly to `false` if you cannot structure your items differently. This might come at a performance penalty though for long lists.
